## This base image is for running latest lbrycrdd
FROM ##
MAINTAINER chamunks [at] gmail [dot] com

ADD https://raw.githubusercontent.com/lbryio/chainquery/master/config/default/chainqueryconfig.toml /etc/chainquery/chainqueryconfig.toml.default
